services:
  backend:
    image: myapp/backend:1.0.0
    container_name: fastapi-backend
    restart: always
    network_mode: "host"    # 🔑 direct access to host’s network

  frontend:
    image: myapp/frontend:1.0.0 
    container_name: react-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge